/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.empresa.vista;

import com.empresa.controladores.EditarProductos;
import com.empresa.controladores.EliminarProductos;
import com.empresa.controladores.InsertarProductos;
import com.empresa.controladores.MostrarProductos;
import com.empresa.modelo.Producto;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ja1020
 */
public class InicioUI extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    ArrayList<Producto> productosTabla = new ArrayList<Producto>();
    
    /**
     * Creates new form InicioUI
     */
    public InicioUI() {
        
        initComponents();
        
        setBounds(0, 0, 470, 650); // posicion inicial de la ventana y su tamaño
        setLocationRelativeTo(this); // ventana en el centro de la pantalla
        //setDefaultCloseOperation(EXIT_ON_CLOSE); //termina el programa al dar clic en el boton CERRAR
        setTitle("Sistema de Control de Inventario."); //establece el Titulo de la ventana principal
        //jTabbedPane1.getTabComponentAt(1).setName("create");
        setUpModel();
    }

    private void setUpModel(){
        ArrayList<Object> nombreColumna = new ArrayList<Object>();
        nombreColumna.add("Id");
        nombreColumna.add("Nombre");
        nombreColumna.add("Precio");
        nombreColumna.add("Cantidad");
        nombreColumna.add("Descripcion");
        
        for(Object columna: nombreColumna){
            this.modelo.addColumn(columna);
        }
        this.jTableReadProductos.setModel(modelo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jCreate = new javax.swing.JPanel();
        jLabelInsertTitulo = new javax.swing.JLabel();
        jLabelInsertNombreProducto = new javax.swing.JLabel();
        jTextFieldInsertNombre = new javax.swing.JTextField();
        jLabelInsertCantidad = new javax.swing.JLabel();
        jTextFieldInsertCantidad = new javax.swing.JTextField();
        jTextFieldInsertPrecio = new javax.swing.JTextField();
        jLabelInsertPrecio = new javax.swing.JLabel();
        jLabelInsertDescripcion = new javax.swing.JLabel();
        jLabelInsertMoneda = new javax.swing.JLabel();
        jTextFieldInsertDescripcion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonInsertAction = new javax.swing.JButton();
        jRead = new javax.swing.JPanel();
        jLabelReadTitulo = new javax.swing.JLabel();
        jScrollPaneRead = new javax.swing.JScrollPane();
        jTableReadProductos = new javax.swing.JTable();
        jLabelReadCantidadProductos = new javax.swing.JLabel();
        jTextFieldReadCantidadProd = new javax.swing.JTextField();
        jUpdate = new javax.swing.JPanel();
        jLabelEditTitulo = new javax.swing.JLabel();
        jLabelEditNumero = new javax.swing.JLabel();
        jTextFieldEditNumero = new javax.swing.JTextField();
        jButtonEditMostrarAction = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanelEditArea = new javax.swing.JPanel();
        jLabelEditNombreProducto = new javax.swing.JLabel();
        jTextFieldEditNombre = new javax.swing.JTextField();
        jLabelEditDescripcion = new javax.swing.JLabel();
        jTextFieldEditDescripcion = new javax.swing.JTextField();
        jTextFieldEditCantidad = new javax.swing.JTextField();
        jLabelEditCantidad = new javax.swing.JLabel();
        jLabelEditPrecio = new javax.swing.JLabel();
        jTextFieldEditPrecio = new javax.swing.JTextField();
        jLabelEditMoneda = new javax.swing.JLabel();
        jButtonEditAction = new javax.swing.JButton();
        jDelete = new javax.swing.JPanel();
        jLabelDeleteTitulo = new javax.swing.JLabel();
        jLabelDeleteProducto = new javax.swing.JLabel();
        jTextFieldDeleteId = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonDeleteAction = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane1MousePressed(evt);
            }
        });

        jCreate.setName("create"); // NOI18N
        jCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCreateMouseClicked(evt);
            }
        });

        jLabelInsertTitulo.setText("Registro de nuevos productos en la tienda");
        jLabelInsertTitulo.setName("titulo"); // NOI18N

        jLabelInsertNombreProducto.setText("Nombre");
        jLabelInsertNombreProducto.setName("nombreProducto"); // NOI18N

        jTextFieldInsertNombre.setToolTipText("");
        jTextFieldInsertNombre.setName("nombreText"); // NOI18N
        jTextFieldInsertNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInsertNombreActionPerformed(evt);
            }
        });

        jLabelInsertCantidad.setText("Cantidad");
        jLabelInsertCantidad.setName("cantidad"); // NOI18N

        jTextFieldInsertCantidad.setToolTipText("");
        jTextFieldInsertCantidad.setName("cantidadText"); // NOI18N
        jTextFieldInsertCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInsertCantidadActionPerformed(evt);
            }
        });

        jTextFieldInsertPrecio.setToolTipText("");
        jTextFieldInsertPrecio.setName("precioText"); // NOI18N
        jTextFieldInsertPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInsertPrecioActionPerformed(evt);
            }
        });

        jLabelInsertPrecio.setText("Precio");
        jLabelInsertPrecio.setName("precio"); // NOI18N

        jLabelInsertDescripcion.setText("Descripción");
        jLabelInsertDescripcion.setName("descripcion"); // NOI18N

        jLabelInsertMoneda.setText("$");
        jLabelInsertMoneda.setName("moneda"); // NOI18N

        jTextFieldInsertDescripcion.setToolTipText("");
        jTextFieldInsertDescripcion.setName("descripcionText"); // NOI18N
        jTextFieldInsertDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInsertDescripcionActionPerformed(evt);
            }
        });

        jButtonInsertAction.setBackground(new java.awt.Color(0, 153, 255));
        jButtonInsertAction.setText("Agregar");
        jButtonInsertAction.setName("agregarAccion"); // NOI18N
        jButtonInsertAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jCreateLayout = new javax.swing.GroupLayout(jCreate);
        jCreate.setLayout(jCreateLayout);
        jCreateLayout.setHorizontalGroup(
            jCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelInsertTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jCreateLayout.createSequentialGroup()
                .addGroup(jCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCreateLayout.createSequentialGroup()
                        .addGroup(jCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelInsertNombreProducto)
                            .addComponent(jLabelInsertCantidad)
                            .addComponent(jLabelInsertPrecio)
                            .addComponent(jLabelInsertDescripcion))
                        .addGap(28, 28, 28)
                        .addGroup(jCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldInsertNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldInsertCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jCreateLayout.createSequentialGroup()
                                .addComponent(jLabelInsertMoneda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldInsertPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldInsertDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jCreateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jCreateLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButtonInsertAction)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jCreateLayout.setVerticalGroup(
            jCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCreateLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelInsertTitulo)
                .addGap(42, 42, 42)
                .addGroup(jCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInsertNombreProducto)
                    .addComponent(jTextFieldInsertNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInsertDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInsertDescripcion))
                .addGap(18, 18, 18)
                .addGroup(jCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInsertCantidad)
                    .addComponent(jTextFieldInsertCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInsertPrecio)
                    .addComponent(jTextFieldInsertPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInsertMoneda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButtonInsertAction)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ingresar Información", jCreate);

        jRead.setName("read"); // NOI18N

        jLabelReadTitulo.setText("Consultar todos los productos en la tienda");
        jLabelReadTitulo.setLocation(new java.awt.Point(-32723, -32676));
        jLabelReadTitulo.setName("consultarTitulo"); // NOI18N

        jScrollPaneRead.setName("scroll"); // NOI18N

        jTableReadProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableReadProductos.setName("tablaProductos"); // NOI18N
        jScrollPaneRead.setViewportView(jTableReadProductos);

        jLabelReadCantidadProductos.setText("Cantidad de Productos");
        jLabelReadCantidadProductos.setName("cantidadTexto"); // NOI18N

        jTextFieldReadCantidadProd.setName("cantidad"); // NOI18N

        javax.swing.GroupLayout jReadLayout = new javax.swing.GroupLayout(jRead);
        jRead.setLayout(jReadLayout);
        jReadLayout.setHorizontalGroup(
            jReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jReadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jReadLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelReadCantidadProductos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldReadCantidadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneRead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelReadTitulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jReadLayout.setVerticalGroup(
            jReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jReadLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabelReadTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneRead, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelReadCantidadProductos)
                    .addComponent(jTextFieldReadCantidadProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar", jRead);

        jUpdate.setName("update"); // NOI18N

        jLabelEditTitulo.setText("Editar productos existentes en la tienda");
        jLabelEditTitulo.setLocation(new java.awt.Point(-32723, -32676));

        jLabelEditNumero.setText("Modificar producto número");

        jTextFieldEditNumero.setName("id"); // NOI18N

        jButtonEditMostrarAction.setBackground(new java.awt.Color(0, 102, 204));
        jButtonEditMostrarAction.setText("Mostrar");
        jButtonEditMostrarAction.setName("buscarAccion"); // NOI18N
        jButtonEditMostrarAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditMostrarActionActionPerformed(evt);
            }
        });

        jPanelEditArea.setToolTipText("");
        jPanelEditArea.setName("panelEditable"); // NOI18N

        jLabelEditNombreProducto.setText("Nombre");

        jTextFieldEditNombre.setName("nombreEditar"); // NOI18N

        jLabelEditDescripcion.setText("Descripción");

        jTextFieldEditDescripcion.setName("descripcionEditar"); // NOI18N

        jTextFieldEditCantidad.setName("cantidadEditar"); // NOI18N

        jLabelEditCantidad.setText("Cantidad");

        jLabelEditPrecio.setText("Precio");

        jTextFieldEditPrecio.setName("precioEditar"); // NOI18N

        jLabelEditMoneda.setText("$");

        jButtonEditAction.setBackground(new java.awt.Color(0, 102, 204));
        jButtonEditAction.setText("Modificar");
        jButtonEditAction.setName("modificarAccion"); // NOI18N
        jButtonEditAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEditAreaLayout = new javax.swing.GroupLayout(jPanelEditArea);
        jPanelEditArea.setLayout(jPanelEditAreaLayout);
        jPanelEditAreaLayout.setHorizontalGroup(
            jPanelEditAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEditDescripcion)
                    .addComponent(jLabelEditNombreProducto)
                    .addComponent(jLabelEditCantidad)
                    .addComponent(jLabelEditPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEditNombre)
                    .addComponent(jTextFieldEditDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelEditAreaLayout.createSequentialGroup()
                        .addGroup(jPanelEditAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEditAction)
                            .addGroup(jPanelEditAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEditAreaLayout.createSequentialGroup()
                                    .addComponent(jLabelEditMoneda)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldEditPrecio))
                                .addComponent(jTextFieldEditCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelEditAreaLayout.setVerticalGroup(
            jPanelEditAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditAreaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelEditAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEditNombreProducto)
                    .addComponent(jTextFieldEditNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelEditAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEditDescripcion)
                    .addComponent(jTextFieldEditDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelEditAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEditCantidad)
                    .addComponent(jTextFieldEditCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelEditAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEditPrecio)
                    .addComponent(jTextFieldEditPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEditMoneda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEditAction)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jUpdateLayout = new javax.swing.GroupLayout(jUpdate);
        jUpdate.setLayout(jUpdateLayout);
        jUpdateLayout.setHorizontalGroup(
            jUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jUpdateLayout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelEditArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEditTitulo)
                    .addGroup(jUpdateLayout.createSequentialGroup()
                        .addComponent(jLabelEditNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldEditNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditMostrarAction)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jUpdateLayout.setVerticalGroup(
            jUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jUpdateLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabelEditTitulo)
                .addGap(23, 23, 23)
                .addGroup(jUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEditNumero)
                    .addComponent(jTextFieldEditNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditMostrarAction))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEditArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Editar", jUpdate);

        jDelete.setName("delete"); // NOI18N

        jLabelDeleteTitulo.setText("Eliminar productos en la tienda");
        jLabelDeleteTitulo.setLocation(new java.awt.Point(-32723, -32676));

        jLabelDeleteProducto.setText("Número de producto");

        jTextFieldDeleteId.setName("eliminarText"); // NOI18N

        jButtonDeleteAction.setBackground(new java.awt.Color(0, 102, 204));
        jButtonDeleteAction.setText("Eliminar");
        jButtonDeleteAction.setName("eliminarAccion"); // NOI18N
        jButtonDeleteAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDeleteLayout = new javax.swing.GroupLayout(jDelete);
        jDelete.setLayout(jDeleteLayout);
        jDeleteLayout.setHorizontalGroup(
            jDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDeleteLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jButtonDeleteAction)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDeleteLayout.createSequentialGroup()
                .addGroup(jDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDeleteLayout.createSequentialGroup()
                        .addComponent(jLabelDeleteProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDeleteId, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 221, Short.MAX_VALUE))
                    .addGroup(jDeleteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDeleteLayout.createSequentialGroup()
                                .addComponent(jLabelDeleteTitulo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator2))))
                .addContainerGap())
        );
        jDeleteLayout.setVerticalGroup(
            jDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDeleteLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabelDeleteTitulo)
                .addGap(82, 82, 82)
                .addGroup(jDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDeleteProducto)
                    .addComponent(jTextFieldDeleteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDeleteAction)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jDelete);

        jLabel1.setFont(new java.awt.Font("Geeza Pro", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("CETIS 54");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Darina Michelle Escobar López");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Axel Nicolás Marin Marinez");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Kury Juárez Garcia");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Humberto Garcia Bacilio");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("Miguel Ángel Rodríguez Núñez");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("Fabián Enrique Moreno Noriega");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Acerca de", jPanel1);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCreateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jCreateMouseClicked

    private void jTabbedPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MousePressed
        // TODO add your handling code here:
        //System.out.println();
        int indice = jTabbedPane1.getSelectedIndex();
        
        switch(indice){
            case 0: // Panel para registrar o crear nuevos productos
                JPanel panel1 = (JPanel) jTabbedPane1.getComponentAt(indice);
                final InsertarProductos insertar = new InsertarProductos( panel1 );
                insertar.limpiarCampos();
                break;
            case 1: 
                // mostrar todos los articulos
                JPanel panel2 = (JPanel) jTabbedPane1.getComponentAt(indice);
                final MostrarProductos consultar = new MostrarProductos( panel2 );
                consultar.cantidadProductos(productosTabla);
                break;
            case 2: 
                // modificar un articulo de todos los disponibles                
                JPanel panel3 = (JPanel) jTabbedPane1.getComponentAt(indice);
                final EditarProductos editar = new EditarProductos( panel3 );
                editar.limpiarCampos();
                break;
            case 3: 
                // eliminar un articulo de todos los disponibles
                // modificar un articulo de todos los disponibles                
                JPanel panel4 = (JPanel) jTabbedPane1.getComponentAt(indice);
                final EliminarProductos eliminar = new EliminarProductos( panel4 );
                eliminar.limpiarCampos();
                break;
            default: break;
        }
        
       // System.out.println("exite el panel? " + panel);
    }//GEN-LAST:event_jTabbedPane1MousePressed

    private void jTextFieldInsertNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInsertNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInsertNombreActionPerformed

    private void jTextFieldInsertCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInsertCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInsertCantidadActionPerformed

    private void jTextFieldInsertPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInsertPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInsertPrecioActionPerformed

    private void jTextFieldInsertDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInsertDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInsertDescripcionActionPerformed

    private void jButtonInsertActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionActionPerformed
        // TODO add your handling code here:
        // boton insertar; un nuevo registro fue presionado
        
        JPanel panel = (JPanel) jTabbedPane1.getComponentAt(0);
        final InsertarProductos insertar = new InsertarProductos( panel );
        boolean isCompleto = insertar.validar();
        if (isCompleto){
            System.out.println( "Inicia la creacion de un objeto Producto> " );
            Producto productoNuevo = insertar.accion();
            if (productoNuevo != null){
                this.productosTabla.add(productoNuevo);
                JOptionPane.showMessageDialog(null, "¡Producto registrado exitosamente!.");
            }
        }
        
        // limpiar los campos
        insertar.limpiarCampos();
        
        // insertar el nuevo registro en el modelo
        insertar.enModelo(this.modelo, this.productosTabla);        
    }//GEN-LAST:event_jButtonInsertActionActionPerformed

    private void jButtonEditMostrarActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditMostrarActionActionPerformed
        // TODO add your handling code here:
        // boton mostrar; se consulta un solo registro para editarlo (si existe)
        int indice = jTabbedPane1.getSelectedIndex();
        JPanel panel = (JPanel) jTabbedPane1.getComponentAt(indice);
        final EditarProductos editar = new EditarProductos( panel );
        editar.mostrarUnProducto(productosTabla);
    }//GEN-LAST:event_jButtonEditMostrarActionActionPerformed

    private void jButtonEditActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionActionPerformed
        // TODO add your handling code here:
        // boton editar; se modifica uno de los articulos
        int indice = jTabbedPane1.getSelectedIndex();
        JPanel panel = (JPanel) jTabbedPane1.getComponentAt(indice);
        final EditarProductos editar = new EditarProductos( panel );
        boolean isCompleto = editar.unProducto(this.modelo, productosTabla);
        if(isCompleto) {
            JOptionPane.showMessageDialog(null, "¡Producto modificado exitosamente!.");
        }
        editar.limpiarCampos();
    }//GEN-LAST:event_jButtonEditActionActionPerformed

    private void jButtonDeleteActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionActionPerformed
        // TODO add your handling code here:
        // boton eliminar; se elimina definitivamente uno de los productos
        int indice = jTabbedPane1.getSelectedIndex();
        JPanel panel = (JPanel) jTabbedPane1.getComponentAt(indice);
        final EliminarProductos eliminar = new EliminarProductos( panel );
        boolean isCompleto = eliminar.unProducto(this.modelo, productosTabla);
        if(isCompleto) {
            JOptionPane.showMessageDialog(null, "¡Producto eliminado exitosamente!.");
        }
        eliminar.limpiarCampos();
    }//GEN-LAST:event_jButtonDeleteActionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDeleteAction;
    private javax.swing.JButton jButtonEditAction;
    private javax.swing.JButton jButtonEditMostrarAction;
    private javax.swing.JButton jButtonInsertAction;
    private javax.swing.JPanel jCreate;
    private javax.swing.JPanel jDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDeleteProducto;
    private javax.swing.JLabel jLabelDeleteTitulo;
    private javax.swing.JLabel jLabelEditCantidad;
    private javax.swing.JLabel jLabelEditDescripcion;
    private javax.swing.JLabel jLabelEditMoneda;
    private javax.swing.JLabel jLabelEditNombreProducto;
    private javax.swing.JLabel jLabelEditNumero;
    private javax.swing.JLabel jLabelEditPrecio;
    private javax.swing.JLabel jLabelEditTitulo;
    private javax.swing.JLabel jLabelInsertCantidad;
    private javax.swing.JLabel jLabelInsertDescripcion;
    private javax.swing.JLabel jLabelInsertMoneda;
    private javax.swing.JLabel jLabelInsertNombreProducto;
    private javax.swing.JLabel jLabelInsertPrecio;
    private javax.swing.JLabel jLabelInsertTitulo;
    private javax.swing.JLabel jLabelReadCantidadProductos;
    private javax.swing.JLabel jLabelReadTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelEditArea;
    private javax.swing.JPanel jRead;
    private javax.swing.JScrollPane jScrollPaneRead;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableReadProductos;
    private javax.swing.JTextField jTextFieldDeleteId;
    private javax.swing.JTextField jTextFieldEditCantidad;
    private javax.swing.JTextField jTextFieldEditDescripcion;
    private javax.swing.JTextField jTextFieldEditNombre;
    private javax.swing.JTextField jTextFieldEditNumero;
    private javax.swing.JTextField jTextFieldEditPrecio;
    private javax.swing.JTextField jTextFieldInsertCantidad;
    private javax.swing.JTextField jTextFieldInsertDescripcion;
    private javax.swing.JTextField jTextFieldInsertNombre;
    private javax.swing.JTextField jTextFieldInsertPrecio;
    private javax.swing.JTextField jTextFieldReadCantidadProd;
    private javax.swing.JPanel jUpdate;
    // End of variables declaration//GEN-END:variables
}
